const schools = window.PSYCHOLOGY_PHD_SCHOOLS || [];
const adjacentRoutes = window.PSYCHOLOGY_PHD_ADJACENT || [];
const state = { filter: "all", search: "" };
const listNode = document.getElementById("school-list");
const emptyNode = document.getElementById("empty-state");
const resultNode = document.getElementById("result-count");
const dialog = document.getElementById("school-dialog");
const dialogContent = document.getElementById("dialog-content");
function escapeHtml(value){return String(value??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function includesSearch(school,query){if(!query)return true;const corpus=[school.name,school.city,school.summary,school.degree,school.study,school.english,school.researchGate,school.workGate,school.biggestRisk,school.fitWhy,...school.tags,...school.directions,...school.requirements,...school.materials,...school.assessment].join(" ").toLowerCase();return corpus.includes(query.toLowerCase())}
function matchesFilter(school){if(state.filter==="all")return true;if(state.filter==="highFit")return school.fit>=4.6;if(state.filter==="hardEnglish")return school.hardEnglish;return school.types.includes(state.filter)}
function badges(school){const items=[];if(school.types.includes("academic"))items.push(["academic","学术博士"]);if(school.types.includes("professional"))items.push(["professional","专业博士"]);if(school.types.includes("parttime"))items.push(["parttime","有非全日制"]);if(school.hardEnglish)items.push(["alert","英语硬线"]);return items.map(([k,l])=>`<span class="badge ${k}">${l}</span>`).join("")}
function renderSchools(){const visible=schools.filter(s=>matchesFilter(s)&&includesSearch(s,state.search));resultNode.textContent=`显示 ${visible.length} / ${schools.length} 所`;emptyNode.hidden=visible.length>0;listNode.innerHTML=visible.map(s=>`<article class="school-card"><div class="school-rank">${s.rank}</div><div><div class="school-title-row"><h3>${escapeHtml(s.name)}</h3>${badges(s)}</div><p class="school-summary">${escapeHtml(s.summary)}</p><div class="tag-row">${s.tags.map(t=>`<span class="tag">${escapeHtml(t)}</span>`).join("")}</div></div><div class="school-facts"><div class="fact"><span>学位路径</span><strong>${escapeHtml(s.degree)}</strong></div><div class="fact"><span>英语</span><strong>${escapeHtml(s.english)}</strong></div><div class="fact"><span>当前周期</span><strong>${escapeHtml(s.cycle)}</strong></div></div><div class="school-score"><div><div class="score-number">${s.fit.toFixed(1)}</div><div class="score-label">方向适配 / 5.0</div></div><button class="detail-button" type="button" data-open-school="${s.id}">查看全部要求</button></div></article>`).join("")}
function itemList(items){return `<ul>${items.map(i=>`<li>${escapeHtml(i)}</li>`).join("")}</ul>`}
function openSchool(id){const s=schools.find(x=>x.id===id);if(!s)return;dialogContent.innerHTML=`<div class="dialog-body"><div class="dialog-hero"><div class="eyebrow">${escapeHtml(s.city)} · 方向适配 ${s.fit.toFixed(1)}/5.0</div><h2>${escapeHtml(s.name)}</h2><p>${escapeHtml(s.summary)}</p></div><div class="dialog-alert"><strong>首要风险：</strong>${escapeHtml(s.biggestRisk)}</div><div class="dialog-grid" style="margin-top:14px"><section class="detail-panel"><h3>学位与学习方式</h3><p>${escapeHtml(s.degree)}</p><p>${escapeHtml(s.study)}</p></section><section class="detail-panel"><h3>英语与科研硬线</h3><p><strong>英语：</strong>${escapeHtml(s.english)}</p><p><strong>科研：</strong>${escapeHtml(s.researchGate)}</p></section><section class="detail-panel"><h3>研究方向</h3>${itemList(s.directions)}</section><section class="detail-panel"><h3>报考条件</h3>${itemList(s.requirements)}</section><section class="detail-panel"><h3>材料清单</h3>${itemList(s.materials)}</section><section class="detail-panel"><h3>考核方式</h3>${itemList(s.assessment)}</section><section class="detail-panel full"><h3>与你的匹配</h3><p>${escapeHtml(s.fitWhy)}</p><p><strong>建议：</strong>${escapeHtml(s.strategy)}</p></section><section class="detail-panel"><h3>目前缺口</h3>${itemList(s.gaps)}</section><section class="detail-panel"><h3>时间与成本</h3><p><strong>周期：</strong>${escapeHtml(s.cycle)}</p><p><strong>成本：</strong>${escapeHtml(s.cost)}</p><p><strong>工作要求：</strong>${escapeHtml(s.workGate)}</p></section><section class="detail-panel full"><h3>官方来源</h3><div class="official-links">${s.sources.map(([l,u])=>`<a href="${escapeHtml(u)}" target="_blank" rel="noreferrer">${escapeHtml(l)} ↗</a>`).join("")}</div></section></div></div>`;dialog.showModal()}
function renderBlockers(){document.getElementById("blocker-table").innerHTML=schools.map(s=>`<tr><td><strong>${escapeHtml(s.name)}</strong></td><td class="${s.hardEnglish?"cell-danger":""}">${escapeHtml(s.blockerRow[0])}</td><td>${escapeHtml(s.blockerRow[1])}</td><td>${escapeHtml(s.blockerRow[2])}</td><td>${escapeHtml(s.blockerRow[3])}</td><td class="cell-caution">${escapeHtml(s.blockerRow[4])}</td></tr>`).join("")}
function renderAdjacent(){document.getElementById("adjacent-list").innerHTML=adjacentRoutes.map(r=>`<article class="adjacent-card"><div class="eyebrow">${escapeHtml(r.code)}</div><h3>${escapeHtml(r.name)}</h3><p>${escapeHtml(r.detail)}</p><div class="adjacent-meta"><strong>授予口径：</strong>${escapeHtml(r.degree)}<br><a href="${escapeHtml(r.source)}" target="_blank" rel="noreferrer">查看官方页面 ↗</a></div></article>`).join("")}
function setMetrics(){document.getElementById("core-count").textContent=schools.length;document.getElementById("professional-count").textContent=schools.filter(s=>s.types.includes("professional")).length;document.getElementById("english-count").textContent=schools.filter(s=>s.hardEnglish).length;document.getElementById("adjacent-count").textContent=adjacentRoutes.length}
document.querySelector(".filter-group").addEventListener("click",e=>{const chip=e.target.closest("[data-filter]");if(!chip)return;state.filter=chip.dataset.filter;document.querySelectorAll("[data-filter]").forEach(n=>n.classList.toggle("active",n===chip));renderSchools()});
document.getElementById("search-input").addEventListener("input",e=>{state.search=e.target.value.trim();renderSchools()});listNode.addEventListener("click",e=>{const b=e.target.closest("[data-open-school]");if(b)openSchool(b.dataset.openSchool)});document.getElementById("dialog-close").addEventListener("click",()=>dialog.close());dialog.addEventListener("click",e=>{const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()});document.getElementById("print-button").addEventListener("click",()=>window.print());setMetrics();renderSchools();renderBlockers();renderAdjacent();
